/********************************************************************************

This file was initially generated by qt's uid tool but is now edited by hand.
Using .ui files was abandoned for this project.

********************************************************************************/

#ifndef MAINWINDOW_UI_H
#define MAINWINDOW_UI_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>

#include "event_handler.h"

QT_BEGIN_NAMESPACE

class MainWindow_Ui
{
public:
    QPushButton * pushButton;
    Radiotelescope::EventHandler * eventHandler;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(800, 600);

        pushButton = new QPushButton("click me!", MainWindow);
        //pushButton->setObjectName("pushButton");

        eventHandler = new Radiotelescope::EventHandler(MainWindow);

        QObject::connect(
            pushButton,
            &QPushButton::clicked,
            eventHandler,
            &Radiotelescope::EventHandler::onBtn1Clicked
        );

        // MainWindow->setCentralWidget(pushButton);

        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Hello Qt!", nullptr));

        // QMetaObject::connectSlotsByName(MainWindow);
    }
};

namespace Ui {
    class MainWindow: public MainWindow_Ui {};
}

QT_END_NAMESPACE

#endif // MAINWINDOW_UI_H
